[package]
name = "lolesports"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mediawiki = "0.2.10"
serde = "1.0.182"
serde_json = "1.0.103"
tokio = "1.29.1"
